name: sews_projet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  bitsdojo_window: any
  calendar_date_picker2: ^0.5.2
  dropdown_button2: ^2.3.7
  excel: ^2.1.0
  file_picker: ^5.3.3
  firedart: ^0.9.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_swipe_action_cell: ^3.1.2
  flutter_styled_toast: ^2.2.1
  get: ^4.6.6
  http: ^1.1.0
  intl: ^0.18.1
  lottie: ^2.6.0
  uuid: ^4.1.0
  flutter_spinkit: ^5.2.0

dependency_overrides:
  win32: ^5.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/

  #   - images/a_dot_ham.jpeg
  fonts:
    - family: kFont
      fonts:
        - asset: fonts/Gilgan.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
